
let token=localStorage.getItem('sx_token'), meta={}, mode='preset', nodes=[], edges=[], chart, profileChart, isothermChart, pendingSource=null;
const $=id=>document.getElementById(id);
function toast(x){$('toast').textContent=x;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};let r=await fetch(url,opt);let j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||'خطا');return j}
function toggleAuth(){ $('authTitle').textContent=$('authTitle').textContent.includes('ورود')?'ثبت‌نام':'ورود به سامانه' }
async function auth(){try{let register=$('authTitle').textContent.includes('ثبت‌نام');let j=await api(register?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('pass').value})});token=j.token;localStorage.setItem('sx_token',token);init()}catch(e){toast(e.message)}}
function logout(){localStorage.removeItem('sx_token');location.reload()}
function show(id,el){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));el.classList.add('active');$('pageTitle').textContent=el.textContent}
async function init(){if(!token){$('login').style.display='grid';return}$('login').style.display='none';$('app').style.display='grid';meta=await api('/api/workbook');let sheets=Object.keys(meta);$('sheet').innerHTML=sheets.filter(s=>meta[s].formula_count>0).map(s=>`<option>${esc(s)}</option>`).join('');$('sheet').onchange=loadInputs;await loadInputs();$('sheetList').innerHTML=sheets.map(s=>`<span class="chip" title="${meta[s].formula_count} formulas">${esc(s)} · ${meta[s].formula_count}</span>`).join('');await scenarios();drawDash();autoCircuit();enablePalette();loadData()}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function loadInputs(){let s=$('sheet').value,m=meta[s];$('inputs').innerHTML=m.inputs.slice(0,24).map(x=>`<div class="field"><label>${esc(x.label||x.cell)} <small>(${x.cell})</small></label><input data-cell="${x.cell}" value="${x.value}"></div>`).join('');$('formulaInfo').innerHTML=`<b>${m.formula_count}</b> فرمول در این شیت ثبت شده است.<br>${m.formula_cells.slice(0,25).join(' · ')}${m.formula_count>25?' …':''}`}
async function calculate(){try{let inputs={};document.querySelectorAll('#inputs input').forEach(i=>{let v=i.value;if(v!=='')inputs[i.dataset.cell]=Number(v)});let j=await api('/api/calculate',{method:'POST',body:JSON.stringify({sheet:$('sheet').value,inputs})});let body=Object.entries(j.values).filter(([k,v])=>typeof v==='number'||typeof v==='string').slice(0,140).map(([k,v])=>`<tr><td>${k}</td><td>${v??''}</td></tr>`).join('');$('results').querySelector('tbody').innerHTML=body;toast('محاسبه با موتور Excel-compatible انجام شد')}catch(e){toast(e.message)}}
async function saveScenario(){try{let name=prompt('نام سناریو؟','Scenario '+new Date().toLocaleString('fa-IR'));if(!name)return;await api('/api/scenarios',{method:'POST',body:JSON.stringify({name,sheet:$('sheet').value,config:{inputs:Object.fromEntries([...document.querySelectorAll('#inputs input')].map(i=>[i.dataset.cell,i.value])),feed:{flow:Number($('feedFlow').value),Cu:Number($('feedCu').value),Fe:Number($('feedFe').value),H2SO4:Number($('feedAcid').value)},nodes,edges}})});toast('سناریو ذخیره شد');scenarios()}catch(e){toast(e.message)}}
async function scenarios(){try{let x=await api('/api/scenarios');$('scount').textContent=x.length}catch{}}
function autoCircuit(){
 nodes=[
 {id:'F',name:'Feed',type:'Feed',x:30,y:175,params:{}},
 {id:'E1',name:'Extraction E1',type:'Ex',x:240,y:80,params:{efficiency:.90,organic_flow_ratio:1}},
 {id:'E2',name:'Extraction E2',type:'Ex',x:240,y:270,params:{efficiency:.93,organic_flow_ratio:1}},
 {id:'RM',name:'Raffinate Mixer',type:'Mixer',x:470,y:185,params:{}},
 {id:'P',name:'Stripper',type:'Px',x:680,y:80,params:{efficiency:.95,aqueous_flow_ratio:1}},
 {id:'EW',name:'Electrowinning',type:'EW',x:900,y:80,params:{cu_deposition:.98}},
 {id:'LO',name:'Lean Organic Mixer',type:'Mixer',x:680,y:280,params:{}}
 ];
 edges=[
 {source:'F',target:'E1',mode:'parallel',fraction:.5,port:'out'}, {source:'F',target:'E2',mode:'parallel',fraction:.5,port:'out'},
 {source:'E1',target:'RM',mode:'series',port:'raffinate'}, {source:'E2',target:'RM',mode:'series',port:'raffinate'},
 {source:'E1',target:'P',mode:'series',port:'organic'}, {source:'E2',target:'P',mode:'series',port:'organic'},
 {source:'P',target:'EW',mode:'series',port:'electrolyte'}, {source:'P',target:'LO',mode:'series',port:'lean_organic'}
 ]; renderFlow('builderFlow');updateJSON();toast('مدار SX‑EW نمونه بارگذاری شد')
}
function addNode(){let id=prompt('شناسه یکتا','N'+(nodes.length+1));if(!id)return;if(nodes.some(n=>n.id===id))return toast('شناسه تکراری است');let type=$('ctype').value;let params={};let eff=Number($('ceff').value||90),ratio=Number($('cratio').value||1),D=Number($('cD').value||0),Q=Number($('cQmax').value||0),K=Number($('cIsoK').value||1),N=Number($('cIsoN').value||1),AE=Number($('cAcidExp').value||0),PR=Number($('cPhaseRec').value||100),DT=Number($('cDisengage').value||0),FE=Number($('cFe').value||0),stageCount=Math.max(1,Number($('cStages').value||1));if(type==='Ex')Object.assign(params,{efficiency:eff,O_A:ratio,D_Cu:D,Qmax_Cu:Q,isotherm_K:K,isotherm_n:N,acid_exponent:AE,phase_recovery:PR,phase_disengagement_time:DT,fe_extraction:FE,stage_count:stageCount});else if(type==='Px')Object.assign(params,{efficiency:eff,A_O:ratio,D_Cu:D,Qmax_Cu:Q,isotherm_K:K,isotherm_n:N,phase_recovery:PR,phase_disengagement_time:DT,stage_count:stageCount});else if(type==='EW')params.cu_deposition=eff;else if(type==='W')params.fe_rejection=eff;else if(type==='S')params.efficiency=eff;nodes.push({id,name:$('cname').value||id,type,x:60+(nodes.length%4)*190,y:45+Math.floor(nodes.length/4)*130,params});renderFlow('builderFlow');updateJSON()}
function expandStageTrain(){let type=$('ctype').value;if(type!=='Ex'&&type!=='Px')return toast('برای Extraction یا Stripper استفاده شود');let count=Math.max(1,Number($('cStages').value||1));if(count===1)return addNode();let base='T'+(nodes.length+1), eff=Number($('ceff').value||90),ratio=Number($('cratio').value||1),D=Number($('cD').value||3),Q=Number($('cQmax').value||.03),K=Number($('cIsoK').value||1),N=Number($('cIsoN').value||1);let made=[];for(let i=1;i<=count;i++){let id=base+(type==='Ex'?'E':'P')+i;let params=type==='Ex'?{efficiency:eff,O_A:ratio,D_Cu:D,Qmax_Cu:Q,isotherm_K:K,isotherm_n:N,stage_count:1}:{efficiency:eff,A_O:ratio,D_Cu:D,Qmax_Cu:Q,isotherm_K:K,isotherm_n:N,stage_count:1};nodes.push({id,name:(type==='Ex'?'Extraction ':'Stripper ')+i,type,x:100+i*170,y:type==='Ex'?70:300,params});made.push(id)}for(let i=0;i<made.length-1;i++){if(type==='Ex')edges.push({source:made[i],target:made[i+1],port:'raffinate'});else edges.push({source:made[i],target:made[i+1],port:'lean_organic'})}toast(count+' مرحله ساخته شد؛ برای Counter-Current مسیر برگشتی را با پورت organic بسازید');renderFlow('builderFlow');updateJSON()}
function updateSelects(){let o=nodes.map(n=>`<option value="${n.id}">${esc(n.name)} (${n.type})</option>`).join('');$('from').innerHTML=o;$('to').innerHTML=o}
function connectNodes(){let f=$('from').value,t=$('to').value;if(!f||!t||f===t)return toast('بلوک مبدأ و مقصد معتبر انتخاب کنید');let frac=$('fraction').value===''?null:Number($('fraction').value);edges.push({source:f,target:t,mode:frac!=null?'parallel':'series',fraction:frac,port:$('fromPort').value,recycle:$('recycleFlag').value==='1'});renderFlow('builderFlow');updateJSON()}
function connectByPorts(a,b,port='out',recycle=false){if(a===b)return;edges.push({source:a,target:b,mode:'series',port,recycle});pendingSource=null;renderFlow('builderFlow');updateJSON()}
function updateJSON(){let circuit={name:'Current Design',feed:{flow:Number($('feedFlow').value),Cu:Number($('feedCu').value),Fe:Number($('feedFe').value),H2SO4:Number($('feedAcid').value)},nodes,edges,solver:{max_iter:Number($('maxIter').value||250),tolerance:Number($('tol').value||1e-8),relaxation:Number($('relax').value||.65)}};$('json').textContent=JSON.stringify(circuit,null,2);updateSelects()}
function renderFlow(id){let c=$(id);c.innerHTML='';nodes.forEach(n=>{let d=document.createElement('div');d.className='node';d.dataset.id=n.id;d.style.left=n.x+'px';d.style.top=n.y+'px';d.innerHTML=`<span class="port in" title="Input"></span><span class="port out" title="Output"></span><b>${esc(n.name)}</b><small>${esc(n.type)} · ${n.id}</small><div class="liveLabel">${n.params?.stage_count>1?'Stages='+n.params.stage_count+' · ':''}${n.params?.D_Cu!=null?'D='+Number(n.params.D_Cu).toFixed(2)+' · ':''}${n.params?.O_A!=null?'O/A='+Number(n.params.O_A).toFixed(2):n.params?.A_O!=null?'A/O='+Number(n.params.A_O).toFixed(2):''}</div>`;d.querySelector('.port.out').onclick=ev=>{ev.stopPropagation();pendingSource=n.id;d.querySelector('.port.out').classList.add('active');toast('بلوک مقصد را انتخاب کنید')};d.querySelector('.port.in').onclick=ev=>{ev.stopPropagation();if(pendingSource){connectByPorts(pendingSource,n.id,'out',false)}};d.onclick=ev=>{if(pendingSource&&pendingSource!==n.id){connectByPorts(pendingSource,n.id,'out',false)}};d.onmousedown=ev=>{if(ev.target.classList.contains('port'))return;dragNode(ev,n,c)};c.appendChild(d)});edges.forEach(e=>{let a=nodes.find(n=>n.id===e.source),b=nodes.find(n=>n.id===e.target);if(!a||!b)return;let x1=a.x+160,y1=a.y+38,x2=b.x,y2=b.y+38;let ar=document.createElement('div');ar.className='arrow';let dx=x2-x1,dy=y2-y1;ar.style.left=x1+'px';ar.style.top=y1+'px';ar.style.width=Math.hypot(dx,dy)+'px';ar.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;ar.title=(e.recycle?'♻ ':'')+(e.port||'out');c.appendChild(ar);let lab=document.createElement('div');lab.className='edgeLabel';lab.style.left=(x1+x2)/2+'px';lab.style.top=(y1+y2)/2-8+'px';lab.textContent=(e.recycle?'♻ ':'')+(e.port||'out');c.appendChild(lab)})}
function dragNode(ev,n,c){ev.preventDefault();let sx=ev.clientX,sy=ev.clientY,ox=n.x,oy=n.y;function move(e){n.x=Math.max(0,ox+e.clientX-sx);n.y=Math.max(0,oy+e.clientY-sy);renderFlow(c.id)}function up(){document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);updateJSON()}document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}
function enablePalette(){document.querySelectorAll('#palette .chip').forEach(p=>p.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',p.dataset.type)));let c=$('builderFlow');c.addEventListener('dragover',e=>e.preventDefault());c.addEventListener('drop',e=>{e.preventDefault();let type=e.dataTransfer.getData('text/plain');if(!type)return;$('ctype').value=type;let r=c.getBoundingClientRect();$('cname').value=type+' '+(nodes.length+1);let id='N'+(nodes.length+1);let params=type==='Ex'?{D_Cu:3,O_A:1,Qmax_Cu:.03,isotherm_K:1,isotherm_n:1}:type==='Px'?{D_Cu:3,A_O:1,Qmax_Cu:.03,isotherm_K:1,isotherm_n:1}:type==='EW'?{cu_deposition:98}:{};nodes.push({id,name:$('cname').value,type,x:e.clientX-r.left-80,y:e.clientY-r.top-25,params});renderFlow('builderFlow');updateJSON()})}
function updateSelects(){let o=nodes.map(n=>`<option value="${n.id}">${esc(n.name)} (${n.type})</option>`).join('');$('from').innerHTML=o;$('to').innerHTML=o}
function connectNodes(){let f=$('from').value,t=$('to').value;if(!f||!t||f===t)return toast('بلوک مبدأ و مقصد معتبر انتخاب کنید');let frac=$('fraction').value===''?null:Number($('fraction').value);edges.push({source:f,target:t,mode:'series',fraction:frac,port:$('fromPort').value,recycle:$('recycleFlag').value==='1'});renderFlow('builderFlow');updateJSON()}
function updateJSON(){let circuit={feed:{flow:Number($('feedFlow').value),Cu:Number($('feedCu').value),Fe:Number($('feedFe').value),H2SO4:Number($('feedAcid').value)},nodes,edges,solver:{max_iter:Number($('maxIter').value||250),tolerance:Number($('tol').value||1e-8),relaxation:Number($('relax').value||.65)}};$('json').textContent=JSON.stringify(circuit,null,2);updateSelects()}
function renderFlow(id){let c=$(id);c.innerHTML='';nodes.forEach(n=>{let d=document.createElement('div');d.className='node';d.style.left=n.x+'px';d.style.top=n.y+'px';d.innerHTML=`<b>${esc(n.name)}</b><small>${esc(n.type)} · ${n.id}</small><div class=\"liveLabel\">${n.params?.D_Cu!=null?'D='+Number(n.params.D_Cu).toFixed(2)+' · ':''}${n.params?.O_A!=null?'O/A='+Number(n.params.O_A).toFixed(2):n.params?.A_O!=null?'A/O='+Number(n.params.A_O).toFixed(2):''}</div>`;d.onmousedown=ev=>dragNode(ev,n,c);c.appendChild(d)});edges.forEach(e=>{let a=nodes.find(n=>n.id===e.source),b=nodes.find(n=>n.id===e.target);if(!a||!b)return;let x1=a.x+145,y1=a.y+35,x2=b.x,y2=b.y+35;let ar=document.createElement('div');ar.className='arrow';let dx=x2-x1,dy=y2-y1;ar.style.left=x1+'px';ar.style.top=y1+'px';ar.style.width=Math.hypot(dx,dy)+'px';ar.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;ar.title=(e.recycle?'♻ ':'')+(e.port||'out');c.appendChild(ar)})}
function dragNode(ev,n,c){ev.preventDefault();let sx=ev.clientX,sy=ev.clientY,ox=n.x,oy=n.y;function move(e){n.x=Math.max(0,ox+e.clientX-sx);n.y=Math.max(0,oy+e.clientY-sy);renderFlow(c.id)}function up(){document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);updateJSON()}document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}
function buildMultiStage(){const N=Math.max(2,Number(prompt('تعداد Extraction/Stripper Stage','4')||4));nodes=[{id:'F',name:'PLS Feed',type:'Feed',x:20,y:190,params:{}}];edges=[];for(let i=1;i<=N;i++)nodes.push({id:'E'+i,name:'Extraction E'+i,type:'Ex',x:170+i*155,y:55,params:{D_Cu:3+i*.2,O_A:1,Qmax_Cu:.03,isotherm_K:1,isotherm_n:1,stage_count:1,fe_extraction:.2}});for(let i=1;i<=N;i++)nodes.push({id:'P'+i,name:'Stripper P'+i,type:'Px',x:170+i*155,y:320,params:{D_Cu:0.4,A_O:1,Qmax_Cu:.03,isotherm_K:1,isotherm_n:1,stage_count:1}});nodes.push({id:'EW',name:'Electrowinning',type:'EW',x:900,y:190,params:{cu_deposition:98}});edges.push({source:'F',target:'E1',port:'out'});for(let i=1;i<N;i++)edges.push({source:'E'+i,target:'E'+(i+1),port:'raffinate',recycle:true});for(let i=N;i>1;i--)edges.push({source:'E'+i,target:'E'+(i-1),port:'organic',recycle:true});edges.push({source:'E1',target:'P1',port:'organic',recycle:true});for(let i=1;i<N;i++)edges.push({source:'P'+i,target:'P'+(i+1),port:'lean_organic',recycle:true});edges.push({source:'P'+N,target:'E'+N,port:'lean_organic',recycle:true});edges.push({source:'P1',target:'EW',port:'electrolyte'});renderFlow('builderFlow');updateJSON();toast('مدار Counter-Current چندمرحله‌ای ساخته شد')}
async function simulateCircuit(){try{updateJSON();let circuit={feed:{flow:Number($('feedFlow').value),Cu:Number($('feedCu').value),Fe:Number($('feedFe').value),H2SO4:Number($('feedAcid').value)},nodes,edges,solver:{max_iter:Number($('maxIter').value||250),tolerance:Number($('tol').value||1e-8),relaxation:Number($('relax').value||.65)}};let j=await api('/api/process/simulate',{method:'POST',body:JSON.stringify({circuit})});let k=j.kpis;$('kpiRec').textContent=Number(k.Cu_recovery_pct).toFixed(2)+'%';$('kpiFeed').textContent=Number(k.feed_flow).toFixed(2);$('kpiCu').textContent=Number(k.product_Cu_mass).toFixed(4);$('kpiBal').textContent=Number(k.mass_balance_error).toExponential(3);$('solverInfo').textContent=`Solver: ${j.solver.converged?'CONVERGED':'NOT CONVERGED'} · iterations=${j.solver.iterations} · residual=${Number(j.solver.residual).toExponential(3)} · recycle=${j.solver.recycle_count}`;$('streamTable').querySelector('tbody').innerHTML=j.streams.map(s=>`<tr><td>${esc(s.id)}</td><td>${Number(s.flow).toFixed(3)}</td><td>${Number(s.Cu).toFixed(6)}</td><td>${Number(s.flow*s.Cu).toFixed(6)}</td><td>${Number(s.Fe).toFixed(6)}</td><td>${Number(s.H2SO4).toFixed(6)}</td><td>${esc(s.phase)}</td><td>${esc(s.port)}</td></tr>`).join('');renderLiveSankey(j.sankey);renderFlow('builderFlow');toast('حلگر Native SX-EW با موازنه جرم اجرا شد')}catch(e){toast(e.message)}}
function renderLiveSankey(links){let box=$('liveSankey');box.innerHTML='<div class="muted" style="margin-bottom:6px">Sankey / Stream Network — ضخامت مفهومی جریان بر اساس Flow</div>';let row=document.createElement('div');row.style.display='flex';row.style.flexWrap='wrap';row.style.gap='7px';links.forEach(l=>{let d=document.createElement('div');d.className='sankLink';d.innerHTML=`<b>${esc(l.source)} → ${esc(l.target)}</b><div class="liveLabel">Flow ${Number(l.value).toFixed(2)} · Cu ${Number(l.Cu_mass).toFixed(3)} kg</div>`;row.appendChild(d)});box.appendChild(row)}

async function analyzeCircuit(){try{updateJSON();let circuit={name:'Current Design',feed:{flow:Number($('feedFlow').value),Cu:Number($('feedCu').value),Fe:Number($('feedFe').value),H2SO4:Number($('feedAcid').value)},nodes,edges,solver:{max_iter:Number($('maxIter').value||250),tolerance:Number($('tol').value||1e-8),relaxation:Number($('relax').value||.65)}};let j=await api('/api/process/analysis',{method:'POST',body:JSON.stringify({circuit})});let p=j.profiles||[];if(profileChart)profileChart.destroy();profileChart=new Chart($('profileChart'),{type:'line',data:{labels:p.map(x=>x.name),datasets:[{label:'Cu in',data:p.map(x=>x.Cu_in)},{label:'Cu out',data:p.map(x=>x.Cu_out)}]},options:{responsive:true}});let pts=(j.isotherms?.[0]?.points||[]);if(isothermChart)isothermChart.destroy();isothermChart=new Chart($('isothermChart'),{type:'line',data:{labels:pts.map(x=>x.C_aq.toFixed(2)),datasets:[{label:'Equilibrium organic',data:pts.map(x=>x.C_org_eq)}]},options:{responsive:true,scales:{x:{title:{display:true,text:'C aqueous'}},y:{title:{display:true,text:'C organic'}}}}});toast('پروفایل Stage و Isotherm آماده شد')}catch(e){toast(e.message)}}
async function compareCurrentVariants(){try{let base={feed:{flow:Number($('feedFlow').value),Cu:Number($('feedCu').value),Fe:Number($('feedFe').value),H2SO4:Number($('feedAcid').value)},nodes,edges,solver:{max_iter:Number($('maxIter').value||250),tolerance:Number($('tol').value||1e-8),relaxation:Number($('relax').value||.65)}};let a=JSON.parse(JSON.stringify(base)),b=JSON.parse(JSON.stringify(base));b.name='Higher O/A';b.nodes.forEach(n=>{if(n.type==='Ex')n.params.O_A=(n.params.O_A||1)*1.2});a.name='Base';let j=await api('/api/process/compare',{method:'POST',body:JSON.stringify({circuits:[a,b]})});$('compareTable').querySelector('tbody').innerHTML=j.scenarios.map(x=>x.error?`<tr><td>${esc(x.name)}</td><td colspan="4" class="danger">${esc(x.error)}</td></tr>`:`<tr><td>${esc(x.name)}</td><td>${Number(x.Cu_recovery_pct).toFixed(3)}</td><td>${Number(x.product_Cu_mass).toFixed(5)}</td><td>${Number(x.mass_balance_error).toExponential(3)}</td><td>${x.iterations}</td></tr>`).join('')}catch(e){toast(e.message)}}

async function addData(){try{let ts=$('dts').value||new Date().toISOString().slice(0,16);await api('/api/data',{method:'POST',body:JSON.stringify({ts:new Date(ts).toISOString(),metric:$('metric').value,value:Number($('dval').value),period:$('period').value})});toast('داده ثبت شد');loadData()}catch(e){toast(e.message)}}
async function loadData(){try{let d=await api('/api/data');$('csv').href='/api/data.csv';$('dataTable').innerHTML='<tr><th>تاریخ</th><th>Metric</th><th>Value</th><th>Period</th></tr>'+d.map(x=>`<tr><td>${new Date(x.ts).toLocaleString('fa-IR')}</td><td>${esc(x.metric)}</td><td>${x.value}</td><td>${x.period}</td></tr>`).join('');let labels=d.map(x=>new Date(x.ts).toLocaleDateString('fa-IR')),vals=d.map(x=>x.value);if(chart)chart.destroy();chart=new Chart($('chart'),{type:'line',data:{labels,datasets:[{label:'Performance',data:vals,tension:.35}]},options:{responsive:true,plugins:{legend:{labels:{color:'#cfe0f3'}}},scales:{x:{ticks:{color:'#91a5bf'}},y:{ticks:{color:'#91a5bf'}}}}})}catch{}}
function drawDash(){renderFlow('dashflow')}
init().catch(e=>toast(e.message));
